# Generated by Django 5.1 on 2024-11-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaliciousApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
