# Generated by Django 5.1 on 2024-11-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaliciousApp', '0002_alter_auth_email_alter_auth_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('predicted_label', models.CharField(max_length=100)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
