# Generated by Django 5.1.3 on 2024-11-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaliciousApp', '0003_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaliciousApp.auth'),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='predicted_label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
